stages:
  - build
  - deploy
  - inspect

build_image:
  stage: build
  script:
    - docker build -t tcn.re/inspectr/inspectr .
    - docker push tcn.re/inspectr/inspectr
  tags:
    - shell

pip_register:
  stage: deploy
  script:
    - pip install setuptools
    - echo -e "[teonite]\nrepository:https://pypi.teonite.net/simple/\nusername:${PYPI_USERNAME}\npassword:${PYPI_PASSWORD}" > ~/.pypirc
    - python setup.py register -r teonite sdist upload -r teonite
  tags:
    - shell

inspect:
  stage: inspect
  script:
    - docker run -v $(pwd):/code -v /home/gitlab-runner/.inspectr_connector.json:/root/.inspectr_connector.json tcn.re/inspectr/inspectr || true
    - docker run -v $(pwd):/code tcn.re/inspectr/inspectr find /code -user root -exec rm -rf "{}" ';' || true
  tags:
    - shell
