pip_register:
  stage: build
  script:
    - python setup.py register -r teonite sdist upload -r teonite
  tags:
    - shell

build_docker:
  stage: build
  script:
    - docker build -t tcn.re/inspectr/inspectr .
    - docker push tcn.re/inspectr/inspectr
    - docker run -v $(pwd):/code -v /home/gitlab-runner/inspectr_connector_docker.json:/root/.inspectr_connector.json tcn.re/inspectr/inspectr
  tags:
    - shell
